"""Data models for the Smart Home / IoT platform.

Every device, event, and configuration is built from these dataclasses.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import StrEnum, auto
from typing import Any
from uuid import uuid4


# ── Enumerations ─────────────────────────────────────────────────────────────

class DeviceType(StrEnum):
    """The type/category of an IoT device."""

    LIGHT = auto()
    SWITCH = auto()
    PLUG = auto()
    MOTION_SENSOR = auto()
    TEMPERATURE_SENSOR = auto()
    HUMIDITY_SENSOR = auto()
    DOOR_SENSOR = auto()
    THERMOSTAT = auto()


class DeviceStatus(StrEnum):
    """The online/offline status of a device."""

    ONLINE = auto()
    OFFLINE = auto()
    ERROR = auto()
    UNKNOWN = auto()


# ── Device State ─────────────────────────────────────────────────────────────

@dataclass
class DeviceState:
    """The current state of a device.

    All fields default to ``None`` so a device only exposes the state attributes
    that are relevant to its type.  Consumers should check for ``None`` before
    reading a field.
    """

    power: bool | None = None
    brightness: int | None = None           # 0 – 100, for lights
    color_temp: int | None = None            # Kelvin, for lights
    color: str | None = None                 # Hex colour, for lights
    temperature: float | None = None         # °C, for sensors / thermostat
    humidity: float | None = None            # %, for humidity sensors
    motion_detected: bool | None = None      # For motion sensors
    door_open: bool | None = None            # For door sensors
    target_temperature: float | None = None  # °C, for thermostat
    hvac_mode: str | None = None             # "heat" / "cool" / "auto" / "off"


# ── Device Properties ────────────────────────────────────────────────────────

@dataclass
class DeviceProperties:
    """Configurable metadata / properties for a device."""

    name: str = ""
    room: str = "default"
    location: str = ""
    manufacturer: str = "Fiona IoT"
    model: str = "v1"
    firmware_version: str = "1.0.0"
    poll_interval: int = 60  # seconds


# ── Device Info ──────────────────────────────────────────────────────────────

def _new_uuid() -> str:
    """Return a fresh UUID4 hex string."""
    return uuid4().hex


def _now() -> datetime:
    """Return the current UTC timestamp."""
    return datetime.now(timezone.utc)


@dataclass
class DeviceInfo:
    """Full descriptor for a device registered in the platform."""

    device_id: str = field(default_factory=_new_uuid)
    device_type: DeviceType = DeviceType.SWITCH
    status: DeviceStatus = DeviceStatus.OFFLINE
    properties: DeviceProperties = field(default_factory=DeviceProperties)
    state: DeviceState = field(default_factory=DeviceState)
    last_seen: datetime | None = None
    created_at: datetime = field(default_factory=_now)
    tags: list[str] = field(default_factory=list)


# ── Device Event ─────────────────────────────────────────────────────────────

@dataclass
class DeviceEvent:
    """An event generated by a device state change."""

    event_id: str = field(default_factory=_new_uuid)
    device_id: str = ""
    event_type: str = "state_changed"
    timestamp: datetime = field(default_factory=_now)
    data: dict[str, Any] = field(default_factory=dict)


# ── Room ─────────────────────────────────────────────────────────────────────

@dataclass
class Room:
    """A logical grouping of devices (e.g. a physical room)."""

    room_id: str = field(default_factory=_new_uuid)
    name: str = ""
    floor: str = "1"
    device_ids: list[str] = field(default_factory=list)


# ── Scene ────────────────────────────────────────────────────────────────────

@dataclass
class Scene:
    """A named snapshot of device states that can be restored on demand."""

    scene_id: str = field(default_factory=_new_uuid)
    name: str = ""
    states: dict[str, dict[str, Any]] = field(default_factory=dict)
    created_at: datetime = field(default_factory=_now)
